"""Stable Source Import quality issue registry."""

from enum import StrEnum

from .types import Severity


class QualityIssueCode(StrEnum):
    SOURCE_FILE_MISSING = "SOURCE_FILE_MISSING"
    SOURCE_FILE_READ_FAILED = "SOURCE_FILE_READ_FAILED"
    SOURCE_HEADER_MISMATCH = "SOURCE_HEADER_MISMATCH"
    SOURCE_FILE_NO_DATA_ROWS = "SOURCE_FILE_NO_DATA_ROWS"
    SOURCE_ROW_MALFORMED = "SOURCE_ROW_MALFORMED"
    SOURCE_REQUIRED_VALUE_MISSING = "SOURCE_REQUIRED_VALUE_MISSING"
    SOURCE_VALUE_PARSE_FAILED = "SOURCE_VALUE_PARSE_FAILED"
    SOURCE_VALUE_OUT_OF_RANGE = "SOURCE_VALUE_OUT_OF_RANGE"
    SOURCE_ENUM_UNKNOWN = "SOURCE_ENUM_UNKNOWN"
    SOURCE_IDENTIFIER_SUSPICIOUS_FORMAT = "SOURCE_IDENTIFIER_SUSPICIOUS_FORMAT"
    SOURCE_ID_DUPLICATE_IDENTICAL = "SOURCE_ID_DUPLICATE_IDENTICAL"
    SOURCE_ID_DUPLICATE_CONFLICT = "SOURCE_ID_DUPLICATE_CONFLICT"
    SOURCE_REFERENCE_INVALID_LITERAL = "SOURCE_REFERENCE_INVALID_LITERAL"
    SOURCE_REFERENCE_AMBIGUOUS = "SOURCE_REFERENCE_AMBIGUOUS"
    SOURCE_REFERENCE_UNRESOLVED = "SOURCE_REFERENCE_UNRESOLVED"
    SOURCE_MEASUREMENT_TIME_UNKNOWN = "SOURCE_MEASUREMENT_TIME_UNKNOWN"
    GRID_CASE_FEEDER_MISSING = "GRID_CASE_FEEDER_MISSING"
    GRID_CASE_FEEDER_AMBIGUOUS = "GRID_CASE_FEEDER_AMBIGUOUS"
    CANONICAL_REQUIRED_FIELD_MISSING = "CANONICAL_REQUIRED_FIELD_MISSING"
    CANONICAL_UNIQUE_CONSTRAINT_VIOLATION = "CANONICAL_UNIQUE_CONSTRAINT_VIOLATION"
    CANONICAL_REFERENCE_INTEGRITY_ERROR = "CANONICAL_REFERENCE_INTEGRITY_ERROR"


DEFAULT_SEVERITY_BY_CODE: dict[QualityIssueCode, Severity] = {
    QualityIssueCode.SOURCE_FILE_MISSING: Severity.ERROR,
    QualityIssueCode.SOURCE_FILE_READ_FAILED: Severity.ERROR,
    QualityIssueCode.SOURCE_HEADER_MISMATCH: Severity.ERROR,
    QualityIssueCode.SOURCE_FILE_NO_DATA_ROWS: Severity.INFO,
    QualityIssueCode.SOURCE_ROW_MALFORMED: Severity.ERROR,
    QualityIssueCode.SOURCE_REQUIRED_VALUE_MISSING: Severity.ERROR,
    QualityIssueCode.SOURCE_VALUE_PARSE_FAILED: Severity.WARNING,
    QualityIssueCode.SOURCE_VALUE_OUT_OF_RANGE: Severity.ERROR,
    QualityIssueCode.SOURCE_ENUM_UNKNOWN: Severity.WARNING,
    QualityIssueCode.SOURCE_IDENTIFIER_SUSPICIOUS_FORMAT: Severity.WARNING,
    QualityIssueCode.SOURCE_ID_DUPLICATE_IDENTICAL: Severity.WARNING,
    QualityIssueCode.SOURCE_ID_DUPLICATE_CONFLICT: Severity.ERROR,
    QualityIssueCode.SOURCE_REFERENCE_INVALID_LITERAL: Severity.WARNING,
    QualityIssueCode.SOURCE_REFERENCE_AMBIGUOUS: Severity.ERROR,
    QualityIssueCode.SOURCE_REFERENCE_UNRESOLVED: Severity.WARNING,
    QualityIssueCode.SOURCE_MEASUREMENT_TIME_UNKNOWN: Severity.WARNING,
    QualityIssueCode.GRID_CASE_FEEDER_MISSING: Severity.WARNING,
    QualityIssueCode.GRID_CASE_FEEDER_AMBIGUOUS: Severity.ERROR,
    QualityIssueCode.CANONICAL_REQUIRED_FIELD_MISSING: Severity.ERROR,
    QualityIssueCode.CANONICAL_UNIQUE_CONSTRAINT_VIOLATION: Severity.ERROR,
    QualityIssueCode.CANONICAL_REFERENCE_INTEGRITY_ERROR: Severity.ERROR,
}
